### ISSUE TITLE
Problema al instalar Odooenv por primera vez en linux mint 17

### ISSUE THREAD

**Issue by DanteMahat** [odoo-l10n-ar/odooenv_l10n_ar#1]
jaysa@jaysa-M15x ~/Odoo/l10n_ar $ odooenv update
Default file: /usr/local/lib/python2.7/dist-packages/odooenv/data/defaults.yml
Traceback (most recent call last):
  File "/usr/local/bin/odooenv", line 1251, in <module>
    r = main()
  File "/usr/local/bin/odooenv", line 1224, in main
    args.func(args)
  File "/usr/local/bin/odooenv", line 93, in update
    odooenv.update(iterate=True, repositories=args.repositories):
  File "/usr/local/lib/python2.7/dist-packages/odooenv/environment.py", line 120, in update
    for name, repository in self.repositories.iteritems():
  File "/usr/local/lib/python2.7/dist-packages/odooenv/environment.py", line 206, in repositories
    for n, r in self._config.sources.repos])
AttributeError: 'Struct' object has no attribute 'hasattr'

**Comment by csrocha** [comment]
Este error no corresponde a este repositorio. Trasladándolo a csrocha/odooenv#4.
